export const transactions = [
  {
    title: "Salary",
    amount: "315",
    paidby: "Client",
    paidusing: "Cash",
    date: "2023-01-20",
    time: "14:20",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "5685",
    paidby: "Client",
    paidusing: "Credit",
    date: "2023-01-12",
    time: "21:30",
    type: "Income",
  },
  {
    title: "Stock Dividend",
    amount: "1274",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-01-14",
    time: "03:52",
    type: "Income",
  },
  {
    title: "Consulting",
    amount: "1305",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-01-13",
    time: "03:15",
    type: "Income",
  },
  {
    title: "Freelance Work",
    amount: "2186",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-01-05",
    time: "23:06",
    type: "Income",
  },
  {
    title: "Medical",
    amount: "873",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2023-01-19",
    time: "19:20",
    type: "Expense",
  },
  {
    title: "Medical",
    amount: "487",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2023-01-25",
    time: "20:14",
    type: "Expense",
  },
  {
    title: "Clothing",
    amount: "990",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-01-01",
    time: "13:39",
    type: "Expense",
  },
  {
    title: "Petrol",
    amount: "571",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-01-16",
    time: "16:33",
    type: "Expense",
  },
  {
    title: "Utilities",
    amount: "684",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-01-08",
    time: "23:40",
    type: "Expense",
  },
  {
    title: "Bonus",
    amount: "276",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-02-05",
    time: "04:49",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "140",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-02-12",
    time: "05:18",
    type: "Income",
  },
  {
    title: "Sale of Items",
    amount: "774",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-02-11",
    time: "02:02",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "431",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-02-21",
    time: "03:18",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "685",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-02-01",
    time: "00:35",
    type: "Income",
  },
  {
    title: "Medical",
    amount: "240",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-02-14",
    time: "18:40",
    type: "Expense",
  },
  {
    title: "Phone Bill",
    amount: "624",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-02-24",
    time: "18:30",
    type: "Expense",
  },
  {
    title: "Medical",
    amount: "583",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-02-13",
    time: "16:34",
    type: "Expense",
  },
  {
    title: "Books",
    amount: "649",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-02-22",
    time: "11:10",
    type: "Expense",
  },
  {
    title: "Dinner with Friends",
    amount: "1018",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-02-03",
    time: "05:12",
    type: "Expense",
  },
  {
    title: "Rental Income",
    amount: "1054",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-03-05",
    time: "22:38",
    type: "Income",
  },
  {
    title: "Bonus",
    amount: "233",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-03-03",
    time: "03:49",
    type: "Income",
  },
  {
    title: "Consulting",
    amount: "190",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-03-14",
    time: "02:46",
    type: "Income",
  },
  {
    title: "Salary",
    amount: "401",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-03-25",
    time: "07:28",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "1063",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-03-24",
    time: "22:53",
    type: "Income",
  },
  {
    title: "Books",
    amount: "875",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-03-17",
    time: "09:55",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "396",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-03-12",
    time: "17:51",
    type: "Expense",
  },
  {
    title: "Electricity Bill",
    amount: "900",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-03-17",
    time: "14:33",
    type: "Expense",
  },
  {
    title: "Books",
    amount: "1093",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-03-12",
    time: "11:16",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "141",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-03-08",
    time: "19:37",
    type: "Expense",
  },
  {
    title: "Stock Dividend",
    amount: "764",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-04-15",
    time: "11:12",
    type: "Income",
  },
  {
    title: "Workshop Fee",
    amount: "577",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-04-12",
    time: "02:48",
    type: "Income",
  },
  {
    title: "Salary",
    amount: "916",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-04-10",
    time: "03:53",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "535",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-04-21",
    time: "10:16",
    type: "Income",
  },
  {
    title: "Salary",
    amount: "368",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-04-23",
    time: "12:33",
    type: "Income",
  },
  {
    title: "Clothing",
    amount: "573",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-04-10",
    time: "09:59",
    type: "Expense",
  },
  {
    title: "WIFI",
    amount: "158",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-04-05",
    time: "13:48",
    type: "Expense",
  },
  {
    title: "Petrol",
    amount: "784",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-04-08",
    time: "20:04",
    type: "Expense",
  },
  {
    title: "Books",
    amount: "670",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-04-20",
    time: "21:53",
    type: "Expense",
  },
  {
    title: "Utilities",
    amount: "220",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-04-01",
    time: "17:23",
    type: "Expense",
  },
  {
    title: "Rental Income",
    amount: "228",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-05-09",
    time: "16:39",
    type: "Income",
  },
  {
    title: "Freelance Work",
    amount: "825",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-05-09",
    time: "18:36",
    type: "Income",
  },
  {
    title: "Sale of Items",
    amount: "439",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-05-18",
    time: "03:55",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "1077",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-05-16",
    time: "05:59",
    type: "Income",
  },
  {
    title: "Workshop Fee",
    amount: "191",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-05-19",
    time: "20:41",
    type: "Income",
  },
  {
    title: "WIFI",
    amount: "713",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-05-27",
    time: "03:23",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "455",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-05-21",
    time: "00:53",
    type: "Expense",
  },
  {
    title: "Groceries",
    amount: "225",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-05-15",
    time: "11:23",
    type: "Expense",
  },
  {
    title: "Electricity Bill",
    amount: "883",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-05-03",
    time: "20:57",
    type: "Expense",
  },
  {
    title: "Dinner",
    amount: "297",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-05-13",
    time: "01:58",
    type: "Expense",
  },
  {
    title: "Interest",
    amount: "396",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-06-14",
    time: "13:57",
    type: "Income",
  },
  {
    title: "Stock Dividend",
    amount: "204",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-06-17",
    time: "19:13",
    type: "Income",
  },
  {
    title: "Stock Dividend",
    amount: "1006",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-06-18",
    time: "00:14",
    type: "Income",
  },
  {
    title: "Workshop Fee",
    amount: "319",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-06-23",
    time: "16:18",
    type: "Income",
  },
  {
    title: "Stock Dividend",
    amount: "524",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-06-28",
    time: "06:48",
    type: "Income",
  },
  {
    title: "Subscription",
    amount: "152",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-06-25",
    time: "15:32",
    type: "Expense",
  },
  {
    title: "Petrol",
    amount: "554",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-06-15",
    time: "13:08",
    type: "Expense",
  },
  {
    title: "Medical",
    amount: "574",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-06-10",
    time: "02:19",
    type: "Expense",
  },
  {
    title: "Dinner",
    amount: "899",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-06-13",
    time: "04:31",
    type: "Expense",
  },
  {
    title: "Subscription",
    amount: "741",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-06-17",
    time: "07:56",
    type: "Expense",
  },
  {
    title: "Salary",
    amount: "848",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-07-19",
    time: "14:01",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "660",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-07-14",
    time: "22:28",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "215",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-07-25",
    time: "18:18",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "105",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-07-12",
    time: "15:31",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "121",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-07-22",
    time: "01:28",
    type: "Income",
  },
  {
    title: "Dinner",
    amount: "313",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-07-18",
    time: "12:36",
    type: "Expense",
  },
  {
    title: "Dinner with Friends",
    amount: "957",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-07-13",
    time: "13:14",
    type: "Expense",
  },
  {
    title: "Clothing",
    amount: "339",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-07-26",
    time: "05:18",
    type: "Expense",
  },
  {
    title: "Petrol",
    amount: "823",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-07-01",
    time: "11:21",
    type: "Expense",
  },
  {
    title: "Utilities",
    amount: "986",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-07-20",
    time: "22:26",
    type: "Expense",
  },
  {
    title: "Stock Dividend",
    amount: "263",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-08-23",
    time: "15:45",
    type: "Income",
  },
  {
    title: "Sale of Items",
    amount: "553",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-08-18",
    time: "21:48",
    type: "Income",
  },
  {
    title: "Consulting",
    amount: "1042",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-08-04",
    time: "10:41",
    type: "Income",
  },
  {
    title: "Stock Dividend",
    amount: "277",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-08-05",
    time: "09:49",
    type: "Income",
  },
  {
    title: "Stock Dividend",
    amount: "287",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-08-19",
    time: "02:45",
    type: "Income",
  },
  {
    title: "Subscription",
    amount: "828",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-08-10",
    time: "02:22",
    type: "Expense",
  },
  {
    title: "Dinner",
    amount: "143",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-08-28",
    time: "09:14",
    type: "Expense",
  },
  {
    title: "Utilities",
    amount: "925",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-08-03",
    time: "12:32",
    type: "Expense",
  },
  {
    title: "Phone Bill",
    amount: "832",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-08-07",
    time: "07:03",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "1017",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-08-05",
    time: "22:35",
    type: "Expense",
  },
  {
    title: "Freelance Work",
    amount: "821",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-09-22",
    time: "04:00",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "266",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-09-17",
    time: "08:11",
    type: "Income",
  },
  {
    title: "Freelance Work",
    amount: "1047",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-09-05",
    time: "23:36",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "794",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-09-20",
    time: "15:21",
    type: "Income",
  },
  {
    title: "Freelance Work",
    amount: "710",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-09-27",
    time: "07:33",
    type: "Income",
  },
  {
    title: "Books",
    amount: "594",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-09-20",
    time: "14:34",
    type: "Expense",
  },
  {
    title: "Groceries",
    amount: "905",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-09-18",
    time: "02:04",
    type: "Expense",
  },
  {
    title: "Phone Bill",
    amount: "769",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-09-25",
    time: "01:35",
    type: "Expense",
  },
  {
    title: "Books",
    amount: "845",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-09-04",
    time: "16:29",
    type: "Expense",
  },
  {
    title: "Dinner",
    amount: "909",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-09-18",
    time: "12:40",
    type: "Expense",
  },
  {
    title: "Workshop Fee",
    amount: "319",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-10-11",
    time: "17:53",
    type: "Income",
  },
  {
    title: "Rental Income",
    amount: "950",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-10-20",
    time: "06:14",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "492",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-10-18",
    time: "14:32",
    type: "Income",
  },
  {
    title: "Sale of Items",
    amount: "176",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-10-11",
    time: "10:57",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "1047",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-10-27",
    time: "10:44",
    type: "Income",
  },
  {
    title: "Phone Bill",
    amount: "711",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-10-09",
    time: "14:41",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "306",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-10-28",
    time: "22:19",
    type: "Expense",
  },
  {
    title: "Groceries",
    amount: "110",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-10-03",
    time: "07:58",
    type: "Expense",
  },
  {
    title: "Petrol",
    amount: "362",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-10-20",
    time: "02:06",
    type: "Expense",
  },
  {
    title: "Clothing",
    amount: "268",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-10-20",
    time: "16:41",
    type: "Expense",
  },
  {
    title: "Rental Income",
    amount: "419",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-11-13",
    time: "23:06",
    type: "Income",
  },
  {
    title: "Consulting",
    amount: "634",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-11-08",
    time: "23:45",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "784",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-11-19",
    time: "05:46",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "296",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-11-14",
    time: "07:09",
    type: "Income",
  },
  {
    title: "Bonus",
    amount: "630",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-11-21",
    time: "15:44",
    type: "Income",
  },
  {
    title: "Electricity Bill",
    amount: "430",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-11-20",
    time: "02:14",
    type: "Expense",
  },
  {
    title: "WIFI",
    amount: "717",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-11-11",
    time: "18:26",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "363",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-11-12",
    time: "07:49",
    type: "Expense",
  },
  {
    title: "WIFI",
    amount: "465",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-11-02",
    time: "13:39",
    type: "Expense",
  },
  {
    title: "Gym Membership",
    amount: "922",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-11-12",
    time: "21:58",
    type: "Expense",
  },
  {
    title: "Bonus",
    amount: "249",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-12-02",
    time: "22:51",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "834",
    paidby: "Client",
    paidusing: "Debit",
    date: "2024-12-28",
    time: "05:03",
    type: "Income",
  },
  {
    title: "Interest",
    amount: "432",
    paidby: "Client",
    paidusing: "Bank Transfer",
    date: "2024-12-12",
    time: "01:04",
    type: "Income",
  },
  {
    title: "Sale of Items",
    amount: "102",
    paidby: "Client",
    paidusing: "Credit",
    date: "2024-12-21",
    time: "02:53",
    type: "Income",
  },
  {
    title: "Contract Payment",
    amount: "780",
    paidby: "Client",
    paidusing: "Cash",
    date: "2024-12-07",
    time: "18:36",
    type: "Income",
  },
  {
    title: "Clothing",
    amount: "626",
    paidby: "Manoj",
    paidusing: "Cash",
    date: "2024-12-27",
    time: "12:13",
    type: "Expense",
  },
  {
    title: "WIFI",
    amount: "479",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-12-26",
    time: "18:49",
    type: "Expense",
  },
  {
    title: "Dinner with Friends",
    amount: "481",
    paidby: "Manoj",
    paidusing: "Bank Transfer",
    date: "2024-12-17",
    time: "23:16",
    type: "Expense",
  },
  {
    title: "Subscription",
    amount: "916",
    paidby: "Manoj",
    paidusing: "Credit",
    date: "2024-12-05",
    time: "16:33",
    type: "Expense",
  },
  {
    title: "Dinner",
    amount: "232",
    paidby: "Manoj",
    paidusing: "Debit",
    date: "2024-12-04",
    time: "21:14",
    type: "Expense",
  },
];

// const months = [
//   "January",
//   "February",
//   "March",
//   "April",
//   "May",
//   "June",
//   "July",
//   "August",
//   "September",
//   "October",
//   "November",
//   "December",
// ];





// const transactionTypes = ["Income", "Expense"];
// const paymentMethods = ["Credit", "Debit", "Cash", "Bank Transfer"];

// const generateTransaction = (month, type) => {
//   const randomAmount = Math.floor(Math.random() * 1000) + 100; // Random amount between 100 and 1100
//   const randomPaymentMethod =
//     paymentMethods[Math.floor(Math.random() * paymentMethods.length)];
//   const titles =
//     type === "Income"
//       ? [
//           "Salary",
//           "Bonus",
//           "Freelance Work",
//           "Consulting",
//           "Rental Income",
//           "Sale of Items",
//           "Contract Payment",
//           "Workshop Fee",
//           "Interest",
//           "Stock Dividend",
//         ]
//       : [
//           "WIFI",
//           "Groceries",
//           "Utilities",
//           "Dinner",
//           "Books",
//           "Medical",
//           "Subscription",
//           "Gym Membership",
//           "Phone Bill",
//           "Clothing",
//           "Dinner with Friends",
//           "Petrol",
//           "Electricity Bill",
//         ];

//   return {
//     title: titles[Math.floor(Math.random() * titles.length)],
//     amount: randomAmount.toString(),
//     paidby: type === "Income" ? "Client" : "Manoj", // Simplified for demonstration
//     paidusing: randomPaymentMethod,
//     date: `2024-${String(month + 1).padStart(2, "0")}-${String(
//       Math.floor(Math.random() * 28) + 1
//     ).padStart(2, "0")}`, // Random day between 1 and 28
//     time: `${String(Math.floor(Math.random() * 24)).padStart(2, "0")}:${String(
//       Math.floor(Math.random() * 60)
//     ).padStart(2, "0")}`,
//     type: type,
//   };
// };

// const generateMonthlyTransactions = () => {
//   const transactions = [];
//   for (let month = 0; month < 12; month++) {
//     for (const type of transactionTypes) {
//       for (let i = 0; i < 5; i++) {
//         // Generate 5 transactions for each type
//         transactions.push(generateTransaction(month, type));
//       }
//     }
//   }
//   console.log(transactions);

//   return transactions;
// };

// export const transaction = generateMonthlyTransactions();
